    version: '3.1'
    services:
      postgresql:
        image: library/postgres:12-alpine
        ports:
        - '3306:3306'
        volumes:
        - ./data:/var/lib/postgresql
        environment:
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=qa
        - POSTGRES_DB=docker_compose_test