    version: '3.1'
    services:
      postgresql:
        image: library/postgres:12-alpine
        ports:
        - '5432:5432'
        volumes:
        - ./data:/var/lib/postgresql
        environment:
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
        - POSTGRES_DB=docker_compose_test