version: '3.1'
services:
  postgres:
    image: postgres
    ports:
      - '8080:8000'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: qa
      POSTGRES_USER: app

